### ISSUE TITLE
Skype for Business

### ISSUE THREAD

**Issue by clburlison** [pbowden-msft/MAUCacheAdmin#1]
Copy paste mistake [9ac09ce#L211](https://github.com/pbowden-msft/MAUCacheAdmin/blob/9ac09cee56534518fe94c5c2d75244851254a7ea/MAUCacheAdmin#L211)

Should be:

``` bash
$MAUID_SKYPE2016
```

**Comment by pbowden-msft** [comment]
Thanks! Fixed in v1.32
