### ISSUE TITLE
Change application id

### ISSUE THREAD

**Issue by masyanru** [pbowden-msft/MAUCacheAdmin#11]
I don't know why, but some macOS devices with office applications in our environment have another IDs in com.microsoft.autoupdate2

```
Applications =     {
        "/Applications/Microsoft Excel.app" =         {
            "Application ID" = XCEL16;
            LCID = 1033;
        };
        "/Applications/Microsoft OneNote.app" =         {
            "Application ID" = ONMC16;
            LCID = 1033;
        };
        "/Applications/Microsoft Outlook.app" =         {
            "Application ID" = OPIM16;
            LCID = 1033;
        };
        "/Applications/Microsoft PowerPoint.app" =         {
            "Application ID" = PPT316;
            LCID = 1033;
        };
        "/Applications/Microsoft Word.app" =         {
            "Application ID" = MSWD16;
            LCID = 1033;
        };
        "/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app" =         {
            "Application ID" = MSau03;
            LCID = 1033;
        };
```
Do you see? It's 16, not 15.
And psMacUpdatesOFFICE.ps1 doesn't download xml and cat files for this IDs.
If I change $MAUID_WORD2016="0409MSWD**16**", everything is ok.
I see in console: 
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Temp\maucache\0409MSWD16.xml Destination: C:\Temp\maucache\16.13.18052304\0409MSWD16.xml".
VERBOSE: Performing the operation "Copy File" on target "Item: C:\Temp\maucache\0409MSWD16.cat Destination: C:\Temp\maucache\16.13.18052304\0409MSWD16.cat".

and in autoupdate.log
[Microsoft AutoUpdate] <Info> Downloading http://srv-sccm-ps/officeupdates/0409MSWD16.xml
[Microsoft AutoUpdate] <Info> Successfully Downloaded http://srv-sccm-ps/officeupdates/0409MSWD16.xml
[Microsoft AutoUpdate] <Info> Found 1 updates.
[Microsoft AutoUpdate] <Info> Request update filtering
[Microsoft AutoUpdate] <Info> Bypass service for MSWD16 update due to old age
[Microsoft AutoUpdate] <Info> No applicable updates to filter
[Microsoft AutoUpdate] <Info> Set update - Main Thread? No, 1 pending update(s).
[Microsoft AutoUpdate] <Info> Check for update - Updates Found: Count 1
[Microsoft AutoUpdate] <Info> Found updates
[Microsoft AutoUpdate] <Info> TemplateAInstall
[Microsoft AutoUpdate] <Info> Begin Downloading Selected Apps Microsoft_Word_16.13.18052304_Updater.pkg [1074.51 MB]: Yes,
[Microsoft AutoUpdate] <Info> Server is Reachable
[Microsoft AutoUpdate] <Info> Downloading update: Word Update 16.13.1 (18052304)
[Microsoft AutoUpdate] <Info> Downloading http://srv-sccm-ps/officeupdates/Microsoft_Word_16.13.18052304_Updater.pkg

**Comment by pbowden-msft** [comment]
Yes. This is a known (bad) side-effect of some early 16.x builds of Office. You'll want to change the local Applications array on the affected devices so that MSWD, XCEL, PPT3, OPIM and ONMC have '15' suffixes instead of '16'.

Thanks, Paul.
