### ISSUE TITLE
Folder name for MRD collateral

### ISSUE THREAD

**Issue by kevinmcox** [pbowden-msft/MAUCacheAdmin#12]
Hey Paul,

Collateral for remote desktop is currently listing the `<key>Update Version</key>` as "983" and as such the collateral is getting put into a folder with that name.

Earlier in March, with MRD 10.1.2 for example, that key and thus folder were "10.1.2" and matched the version being delivered by the package.

Not sure if this is intended or not but wanted to point it out since it doesn't match the behavior of other applications being downloaded by the MAUCacheAdmin tool.

Thanks!

**Comment by pbowden-msft** [comment]
Yes, by design. Remote Desktop uses a slightly odd way of versioning.
