### ISSUE TITLE
Microsoft Auto Update 4.13 - Not available

### ISSUE THREAD

**Issue by ghost** [pbowden-msft/MAUCacheAdmin#20]
Hello,
I have updated to the newest version of MAUCacheAdmin but I am not seeing 4.13 collateral or .pkg being downloaded. I have received all updates for Office Version 16.27 (Build 19071500)

https://docs.microsoft.com/en-us/officeupdates/release-history-microsoft-autoupdate
**July 2019 release**
Release Date: July 16, 2019
Microsoft Auto Update 4.13

Thanks.

**Comment by pbowden-msft** [comment]
This is by design. MAU 4.13 is currently published as an optional component so MAUCacheAdmin (and MAU itself) won’t see it until it becomes a mandatory release. This normally happens within 72 hours of production release day.
