### ISSUE TITLE
MAUCacheAdmin - download specific version

### ISSUE THREAD

**Issue by scottlep** [pbowden-msft/MAUCacheAdmin#22]
Our network security team recently blocked all downloads from the MS CDNs, yay. I am working on building in-house cache and manifest servers. I have it all working. My question is how do we (or can we even) specify a version that MAUCacheAdmin downloads? For instance, we stay one release behind, current version we are deploying being 16.28 but MAUCacheAdmin pulled down everything for 16.29. Is it possible to specify the version to cache? Can't see to find this info anywhere.

Thanks!!!
Scott

**Comment by pbowden-msft** [comment]
@scottlep yikes, your network security team sounds a little extreme. While you can't specify a version for MAUCacheAdmin to download (i.e. it will always download 'latest), both the collateral and pkg files will accumulate on your server as the months go by, so implicitly, you'll be able to control which version is served up as time goes on.
If you're in a crunch, and need to get the 16.28 upgrade files, a brute force mechanism is to download the 16.28 collateral from https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MAU_16.28.0_19081202.dmg and `curl` all of the PKG urls you find in there. Hope this helps!

**Comment by kevinmcox** [comment]
Once you get things up and running you'll already have the old files in your cache from the previous month's run.

Ha! Paul beat me to it with a better reply.

**Comment by scottlep** [comment]
Thanks all. Yes, extreme. We are a large Pharma. They blocked the CDNs to stop our Windows users from getting MSO versions they shouldn't have. Screws us in the long run, since now I have to take a laptop home, run MAUCacheAdmin from my home network then when back on the corp network upload the cache repo to the server. Fun stuff.

I will try the brute force method, or convince my superiors that we should just start with 16.29, then we can control better after that.

**Comment by pbowden-msft** [comment]
@scottlep tangentially, Office for PC/Windows clients usually hit the CDN through the `officecdn.microsoft.com` URL, whereas on Mac, we use `officecdn-microsoft-com.akamaized.net`URL. Did they block both?

**Comment by scottlep** [comment]
It appears that they have blocked everything they could find. Was working fine using MS' CDNs, then suddenly stopped working. Found out that they started blocking MS downloads and that's what the msupdate logs seem to point to. Works fine off our network, msupdate fails on the network.

**Comment by pbowden-msft** [comment]
Closing.
