### ISSUE TITLE
Not pulling down current version of OneDrive

### ISSUE THREAD

**Issue by scottlep** [pbowden-msft/MAUCacheAdmin#26]
MauCacheAdmin is not pulling down current version of OneDrive. Current version shown at macadmins.software is 19.174.0902. MCA only pulls down 19.086.0502 installer and manifest reflects the same.

Thanks,
Scott

**Comment by pbowden-msft** [comment]
@scottlep this is by design. MAU acts as a backup mechanism for providing OneDrive updates. Typically, OneDrive will update itself through its own XPC updater. 
MAUCacheAdmin inherits this design from core MAU.
