### ISSUE TITLE
Cannot fetch latest pkg versions

### ISSUE THREAD

**Issue by shoopdawoop** [pbowden-msft/MAUCacheAdmin#28]
Pardon my ignorance,

while I am able to fetch the latest Packages (as shown by OfficeCDNCheck) with InstallerCache, e.g. Microsoft_Word_16.16.20021000_Installer.pkg and Microsoft_AutoUpdate_4.20.20021800_Updater.pkg, MAUCacheAdmin only lets me fetch older versions 16.16.18111001 and AutoUpdater 4.5.18110402.

Is this expected behaviour (and if so, why) or am I doing it wrong?

Thanks

**Comment by kevinmcox** [comment]
Are you sure you have the latest version of MAUCacheAdmin? There is code to pull installers/updaters for both Office 2016 and Office 2019.

**Comment by shoopdawoop** [comment]
Ah, that was it, thank you!

For some reason I was still at v2.0.

**Comment by kevinmcox** [comment]
Great, glad we got it sorted out.
