### ISSUE TITLE
MAU v4.23.20051002 missing?

### ISSUE THREAD

**Issue by scottlep** [pbowden-msft/MAUCacheAdmin#30]
MAU v4.23.20051002 seems to be missing in the repository. Latest manifests and pkgs seem to be for v4.22.20042003 when pulling down new manifests/pkgs with MAUCacheAdmin.

Thanks,
Scott

**Comment by kevinmcox** [comment]
4.23 never got added to the catalogs. 4.24 will release today and is scheduled to be added to the catalogs on Thursday.

There is a new MAU tracking page that @pbowden-msft just put online this past weekend: https://macadmins.software/mau/

**Comment by scottlep** [comment]
Ok. Thanks for that info.

**Comment by scottlep** [comment]
It looks like MSO 16.38 updates dropped today, but MAU is still showing as 4.22.2042003 for the latest. Do we know when 4.24 will be added?

Channel: Prod 
   Provider: Akamai 
     Application: 0409MSAU04 - 4.22.20042003           0409MSAU04-CHK - 4.22.20042003
     Application: 0409MSWD15 - 16.16.20061500          0409MSWD15-CHK - 16.16.20061500
     Application: 0409MSWD2019 - 16.38.20061401        0409MSWD2019-CHK - 16.38.20061401
     Application: 0409XCEL15 - 16.16.20061500          0409XCEL15-CHK - 16.16.20061500
     Application: 0409XCEL2019 - 16.38.20061401        0409XCEL2019-CHK - 16.38.20061401
     Application: 0409PPT315 - 16.16.20061500          0409PPT315-CHK - 16.16.20061500
     Application: 0409PPT32019 - 16.38.20061401        0409PPT32019-CHK - 16.38.20061401
     Application: 0409OPIM15 - 16.16.20061500          0409OPIM15-CHK - 16.16.20061500
     Application: 0409OPIM2019 - 16.38.20061401        0409OPIM2019-CHK - 16.38.20061401
     Application: 0409ONMC15 - 16.16.20061500          0409ONMC15-CHK - 16.16.20061500
     Application: 0409ONMC2019 - 16.38.20061401        0409ONMC2019-CHK - 16.38.20061401
     Application: 0409ONDR18 - Undetermined            0409ONDR18-CHK - 99999
     Application: 0409TEAM01 - 129053                  0409TEAM01-CHK - 0
     Application: 0409MSOF14 - 14.7.7                  0409MSOF14-CHK - 14.7.9
     Application: 0409UCCP14 - 14.4.3                  0409UCCP14-CHK - 14.4.3
     Application: 0409MSFB16 - 16.28.192               0409MSFB16-CHK - 16.28.192
     Application: 0409MSRD10 - 1801                    0409MSRD10-CHK - 99999
     Application: 0409IMCP01 - 52.2005001.000          0409IMCP01-CHK - 99999
     Application: 0409EDBT01 - 84.522.20061220         0409EDBT01-CHK - 84.522.20061220
     Application: 0409EDCN01 - 85.549.2006150          0409EDCN01-CHK - 85.549.2006150
     Application: 0409EDDV01 - 85.545.2006110          0409EDDV01-CHK - 85.545.2006110
     Application: 0409WDAV00 - 101.00.31               0409WDAV00-CHK - 101.00.31

**Comment by kevinmcox** [comment]
MAU 4.24 release is on hold per this page: https://macadmins.software/mau/

There has been a lot of discussion around this in the [MacAdmins Slack](https://www.macadmins.org), there was a late breaking issue that we all asked to have fixed before the release.
