### ISSUE TITLE
Content-Length vs. content-length

### ISSUE THREAD

**Issue by meta-github** [pbowden-msft/MAUCacheAdmin#32]
Maybe, it is our proxy, maybe not...

If I execute e.g. `curl --head -s https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Word_16.30.19101301_Updater.pkg`, then I get all header fields in lowercase, e.g. `content-length: 1062155591`. The problem is that `MAUCacheAdmin` matches in a case-sensitive-way: `awk '/Content-Length/` and fails to find the data.

It all ends up with `expr: syntax error`, then `MAUCacheAdmin` assuming that the download is corrupt and redownloading...

**Comment by kevinmcox** [comment]
Are you running the latest version? This sounds like the issue that got fixed last month:
https://github.com/pbowden-msft/MAUCacheAdmin/commit/87c34c15c9323b466bf73e0011130107cd0387dd

**Comment by meta-github** [comment]
Yes, correct. I just thought that I was running the latest version, but I did not.
