### ISSUE TITLE
"function: not found" under sh on Ubuntu 16.04.1

### ISSUE THREAD

**Issue by gabrielsanna** [pbowden-msft/MAUCacheAdmin#4]
When running MAUCacheAdmin under Ubuntu 16.04.1, I got the error `/usr/local/MAUCacheAdmin: 33: /usr/local/MAUCacheAdmin: function: not found`. This is because the `function` keyword is specific to bash—under the sh shell, parenthesis are expected.

Changing the shebang to #!/bin/bash fixed the problem. You could also make the syntax more portable by changing the functions to the proper parenthetical form, i.e.:

`foo () {`   
`   echo "hello world"`
`}`

**Comment by dnikles** [comment]
This was fixed in bug #2  looks like it regressed

**Comment by pbowden-msft** [comment]
Fixed function naming in 1.37
