### ISSUE TITLE
New Edge Updater Content

### ISSUE THREAD

**Issue by nixtar** [pbowden-msft/MAUCacheAdmin#43]
Hello,

While looking at the logs for some of our MAU Cache servers I'm seeing failed requests for newer versions of Edge that MAU shouldn't be aware of...
EG: `MicrosoftEdgeUpdate-117.0.2045.55.pkg`

Only possibility I can think of is that the new Edge Updater is trying to use the MAU Cache Server setting?

If this is the case, it would be good if there was a known way to cache these files.

I'll keep investigating on our end and update this as I find more details.

**Comment by pbowden-msft** [comment]
@nixtar yes, we're seeing cases where the Edge publishing pipelines are pushing newer 0409EDGE01.xml collateral files to the Office CDN, which causes MAU components to detect updates. When this happens, I've been reverting the collateral back to the last supported build (113.1774.23052457). I'm working on a way to fix this.

**Comment by nixtar** [comment]
Ahh it all makes sense now 👍.

Thanks for the info I'll ignore them in the meantime.
