### ISSUE TITLE
New Teams App

### ISSUE THREAD

**Issue by nixtar** [pbowden-msft/MAUCacheAdmin#44]
Hello,

With the new Teams app coming out, MS decided to rename `Microsoft Teams.app` to `Microsoft Teams classic.app`.
And the new Teams client is named `Microsoft Teams (work or school).app` with BundleID of `com.microsoft.teams2`.
Are there going to be new collaterals for the new Teams client or does MAU no longer manage the updates for the new Teams?

On a side note, in our MAU MDM Config Payload we specify the Applications array and now that the teams app has been renamed it appears that MAU is no longer managing it. Should we be adding a duplicate entry for `/Applications/Microsoft Teams.app` with the path `/Applications/Microsoft Teams classic.app`?

Thanks,
Nick

**Comment by nixtar** [comment]
Ahhh, just as I posted this I found it in the MAU logs with the new Teams app installed:

0409TEAMS21

I'll submit a PR to update the MAU Script and PS Module soon. :)

**Comment by pbowden-msft** [comment]
@nixtar Thanks! Yes, the Teams rename has been a bit of a fiasco. On the Applications array side, you'll want to have 2 entries:
   "/Applications/Microsoft Teams classic.app" with an Application ID of "TEAMS10"
   "/Applications/Microsoft Teams (work or school).app" with an Application ID of "TEAMS21"
