### ISSUE TITLE
Typo error - extra '/' character ?

### ISSUE THREAD

**Issue by n9t12ne** [pbowden-msft/MAUCacheAdmin#7]
Every of defined values of **CHANNEL_COLLATERAL_*** ends with '/' symbol

URL for downloading `builds.txt` by curl, looks like:
`http://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac//builds.txt` - double symbol '/' before `builds.txt`

Here - duplicated '/' character appears
https://github.com/pbowden-msft/MAUCacheAdmin/blob/0bff64dac08cfed7b7207465a21d237cb5192437/MAUCacheAdmin#L117

should be (if I'm not mistaken):
`(cd "$SCRATCH_AREA" && curl --progress-bar --remote-name --location "$CHANNELURL""builds.txt") `

**Comment by pbowden-msft** [comment]
Thanks for catching! Fixed in v1.9
